-- Expanded built-in exercise library (PRD 6.1.1: "roughly 200 common exercises"). Additive to the ~19
-- already in supabase/seed.sql — run this after seed.sql. Idempotent via the same
-- exercises_unique_system_name partial index every system-exercise insert already relies on.

insert into public.exercises (user_id, name, category, muscle_groups, equipment, tracking_type, is_system) values
  -- ============ PUSH: chest, shoulders, triceps ============
  (null, 'Incline Barbell Bench Press', 'push', array['chest','shoulders','triceps'], 'barbell', 'weight_reps', true),
  (null, 'Decline Barbell Bench Press', 'push', array['chest','triceps'], 'barbell', 'weight_reps', true),
  (null, 'Close-Grip Bench Press', 'push', array['triceps','chest'], 'barbell', 'weight_reps', true),
  (null, 'Push Press', 'push', array['shoulders','triceps'], 'barbell', 'weight_reps', true),
  (null, 'Barbell Skull Crusher', 'push', array['triceps'], 'barbell', 'weight_reps', true),
  (null, 'Incline Dumbbell Press', 'push', array['chest','shoulders'], 'dumbbell', 'weight_reps', true),
  (null, 'Decline Dumbbell Press', 'push', array['chest','triceps'], 'dumbbell', 'weight_reps', true),
  (null, 'Dumbbell Flye', 'push', array['chest'], 'dumbbell', 'weight_reps', true),
  (null, 'Incline Dumbbell Flye', 'push', array['chest'], 'dumbbell', 'weight_reps', true),
  (null, 'Dumbbell Lateral Raise', 'push', array['shoulders'], 'dumbbell', 'weight_reps', true),
  (null, 'Dumbbell Front Raise', 'push', array['shoulders'], 'dumbbell', 'weight_reps', true),
  (null, 'Dumbbell Arnold Press', 'push', array['shoulders','triceps'], 'dumbbell', 'weight_reps', true),
  (null, 'Dumbbell Tricep Kickback', 'push', array['triceps'], 'dumbbell', 'weight_reps', true),
  (null, 'Dumbbell Overhead Tricep Extension', 'push', array['triceps'], 'dumbbell', 'weight_reps', true),
  (null, 'Dumbbell Floor Press', 'push', array['chest','triceps'], 'dumbbell', 'weight_reps', true),
  (null, 'Chest Press Machine', 'push', array['chest','triceps'], 'machine', 'weight_reps', true),
  (null, 'Pec Deck Machine', 'push', array['chest'], 'machine', 'weight_reps', true),
  (null, 'Shoulder Press Machine', 'push', array['shoulders','triceps'], 'machine', 'weight_reps', true),
  (null, 'Tricep Extension Machine', 'push', array['triceps'], 'machine', 'weight_reps', true),
  (null, 'Incline Chest Press Machine', 'push', array['chest','shoulders'], 'machine', 'weight_reps', true),
  (null, 'Cable Chest Fly', 'push', array['chest'], 'cable', 'weight_reps', true),
  (null, 'Cable Crossover', 'push', array['chest'], 'cable', 'weight_reps', true),
  (null, 'Cable Lateral Raise', 'push', array['shoulders'], 'cable', 'weight_reps', true),
  (null, 'Cable Overhead Tricep Extension', 'push', array['triceps'], 'cable', 'weight_reps', true),
  (null, 'Cable Front Raise', 'push', array['shoulders'], 'cable', 'weight_reps', true),
  (null, 'Dip', 'push', array['chest','triceps'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Diamond Push-Up', 'push', array['triceps','chest'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Incline Push-Up', 'push', array['chest','triceps'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Decline Push-Up', 'push', array['chest','shoulders'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Pike Push-Up', 'push', array['shoulders','triceps'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Wall Handstand Push-Up', 'push', array['shoulders','triceps'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Band Chest Press', 'push', array['chest','triceps'], 'band', 'weight_reps', true),
  (null, 'Band Lateral Raise', 'push', array['shoulders'], 'band', 'weight_reps', true),
  (null, 'Band Tricep Pushdown', 'push', array['triceps'], 'band', 'weight_reps', true),
  (null, 'Band Overhead Press', 'push', array['shoulders','triceps'], 'band', 'weight_reps', true),

  -- ============ PULL: back, biceps, traps, rear delts ============
  (null, 'Barbell Shrug', 'pull', array['back'], 'barbell', 'weight_reps', true),
  (null, 'Pendlay Row', 'pull', array['back','biceps'], 'barbell', 'weight_reps', true),
  (null, 'T-Bar Row', 'pull', array['back','biceps'], 'barbell', 'weight_reps', true),
  (null, 'Barbell Upright Row', 'pull', array['shoulders','back'], 'barbell', 'weight_reps', true),
  (null, 'Barbell Curl', 'pull', array['biceps'], 'barbell', 'weight_reps', true),
  (null, 'Barbell Preacher Curl', 'pull', array['biceps'], 'barbell', 'weight_reps', true),
  (null, 'Single-Arm Dumbbell Row', 'pull', array['back','biceps'], 'dumbbell', 'weight_reps', true),
  (null, 'Dumbbell Rear Delt Flye', 'pull', array['shoulders','back'], 'dumbbell', 'weight_reps', true),
  (null, 'Dumbbell Shrug', 'pull', array['back'], 'dumbbell', 'weight_reps', true),
  (null, 'Dumbbell Hammer Curl', 'pull', array['biceps'], 'dumbbell', 'weight_reps', true),
  (null, 'Dumbbell Concentration Curl', 'pull', array['biceps'], 'dumbbell', 'weight_reps', true),
  (null, 'Dumbbell Pullover', 'pull', array['back','chest'], 'dumbbell', 'weight_reps', true),
  (null, 'Chest-Supported Dumbbell Row', 'pull', array['back','biceps'], 'dumbbell', 'weight_reps', true),
  (null, 'Incline Dumbbell Curl', 'pull', array['biceps'], 'dumbbell', 'weight_reps', true),
  (null, 'Row Machine', 'pull', array['back','biceps'], 'machine', 'weight_reps', true),
  (null, 'Assisted Pull-Up Machine', 'pull', array['back','biceps'], 'machine', 'weight_reps', true),
  (null, 'Reverse Pec Deck', 'pull', array['shoulders','back'], 'machine', 'weight_reps', true),
  (null, 'Seated Cable Row', 'pull', array['back','biceps'], 'cable', 'weight_reps', true),
  (null, 'Straight-Arm Pulldown', 'pull', array['back'], 'cable', 'weight_reps', true),
  (null, 'Single-Arm Cable Row', 'pull', array['back','biceps'], 'cable', 'weight_reps', true),
  (null, 'Cable Bicep Curl', 'pull', array['biceps'], 'cable', 'weight_reps', true),
  (null, 'Cable Hammer Curl', 'pull', array['biceps'], 'cable', 'weight_reps', true),
  (null, 'Cable Rear Delt Flye', 'pull', array['shoulders','back'], 'cable', 'weight_reps', true),
  (null, 'Cable Shrug', 'pull', array['back'], 'cable', 'weight_reps', true),
  (null, 'Chin-Up', 'pull', array['back','biceps'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Inverted Row', 'pull', array['back','biceps'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Australian Pull-Up', 'pull', array['back','biceps'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Band Row', 'pull', array['back','biceps'], 'band', 'weight_reps', true),
  (null, 'Band Pull-Apart', 'pull', array['shoulders','back'], 'band', 'weight_reps', true),
  (null, 'Band Bicep Curl', 'pull', array['biceps'], 'band', 'weight_reps', true),

  -- ============ LEGS: quads, hamstrings, glutes, calves ============
  (null, 'Front Squat', 'legs', array['quadriceps','glutes'], 'barbell', 'weight_reps', true),
  (null, 'Romanian Deadlift', 'legs', array['hamstrings','glutes'], 'barbell', 'weight_reps', true),
  (null, 'Sumo Deadlift', 'legs', array['hamstrings','glutes','back'], 'barbell', 'weight_reps', true),
  (null, 'Barbell Hip Thrust', 'legs', array['glutes','hamstrings'], 'barbell', 'weight_reps', true),
  (null, 'Barbell Lunge', 'legs', array['quadriceps','glutes'], 'barbell', 'weight_reps', true),
  (null, 'Barbell Good Morning', 'legs', array['hamstrings','glutes'], 'barbell', 'weight_reps', true),
  (null, 'Barbell Calf Raise', 'legs', array['calves'], 'barbell', 'weight_reps', true),
  (null, 'Zercher Squat', 'legs', array['quadriceps','glutes'], 'barbell', 'weight_reps', true),
  (null, 'Box Squat', 'legs', array['quadriceps','glutes'], 'barbell', 'weight_reps', true),
  (null, 'Dumbbell Lunge', 'legs', array['quadriceps','glutes'], 'dumbbell', 'weight_reps', true),
  (null, 'Dumbbell Bulgarian Split Squat', 'legs', array['quadriceps','glutes'], 'dumbbell', 'weight_reps', true),
  (null, 'Dumbbell Romanian Deadlift', 'legs', array['hamstrings','glutes'], 'dumbbell', 'weight_reps', true),
  (null, 'Dumbbell Step-Up', 'legs', array['quadriceps','glutes'], 'dumbbell', 'weight_reps', true),
  (null, 'Dumbbell Calf Raise', 'legs', array['calves'], 'dumbbell', 'weight_reps', true),
  (null, 'Dumbbell Goblet Squat', 'legs', array['quadriceps','glutes'], 'dumbbell', 'weight_reps', true),
  (null, 'Dumbbell Sumo Squat', 'legs', array['quadriceps','glutes'], 'dumbbell', 'weight_reps', true),
  (null, 'Leg Extension Machine', 'legs', array['quadriceps'], 'machine', 'weight_reps', true),
  (null, 'Seated Leg Curl Machine', 'legs', array['hamstrings'], 'machine', 'weight_reps', true),
  (null, 'Hip Abduction Machine', 'legs', array['glutes'], 'machine', 'weight_reps', true),
  (null, 'Hip Adduction Machine', 'legs', array['glutes'], 'machine', 'weight_reps', true),
  (null, 'Calf Raise Machine', 'legs', array['calves'], 'machine', 'weight_reps', true),
  (null, 'Hack Squat Machine', 'legs', array['quadriceps','glutes'], 'machine', 'weight_reps', true),
  (null, 'Glute Kickback Machine', 'legs', array['glutes'], 'machine', 'weight_reps', true),
  (null, 'Smith Machine Squat', 'legs', array['quadriceps','glutes'], 'machine', 'weight_reps', true),
  (null, 'Cable Kickback', 'legs', array['glutes'], 'cable', 'weight_reps', true),
  (null, 'Cable Pull-Through', 'legs', array['hamstrings','glutes'], 'cable', 'weight_reps', true),
  (null, 'Bodyweight Squat', 'legs', array['quadriceps','glutes'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Walking Lunge', 'legs', array['quadriceps','glutes'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Glute Bridge', 'legs', array['glutes','hamstrings'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Wall Sit', 'legs', array['quadriceps'], 'bodyweight', 'time', true),
  (null, 'Single-Leg Glute Bridge', 'legs', array['glutes'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Nordic Hamstring Curl', 'legs', array['hamstrings'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Pistol Squat', 'legs', array['quadriceps','glutes'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Bodyweight Calf Raise', 'legs', array['calves'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Banded Squat', 'legs', array['quadriceps','glutes'], 'band', 'weight_reps', true),
  (null, 'Banded Glute Bridge', 'legs', array['glutes'], 'band', 'weight_reps', true),
  (null, 'Banded Hip Thrust', 'legs', array['glutes'], 'band', 'weight_reps', true),

  -- ============ CORE ============
  (null, 'Sit-Up', 'core', array['core'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Crunch', 'core', array['core'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Bicycle Crunch', 'core', array['core'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Russian Twist', 'core', array['core'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Mountain Climber', 'core', array['core','cardio'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Leg Raise', 'core', array['core'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'V-Up', 'core', array['core'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Side Plank', 'core', array['core'], 'bodyweight', 'time', true),
  (null, 'Dead Bug', 'core', array['core'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Flutter Kick', 'core', array['core'], 'bodyweight', 'time', true),
  (null, 'Bird Dog', 'core', array['core'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Hollow Body Hold', 'core', array['core'], 'bodyweight', 'time', true),
  (null, 'Cable Crunch', 'core', array['core'], 'cable', 'weight_reps', true),
  (null, 'Cable Woodchopper', 'core', array['core'], 'cable', 'weight_reps', true),
  (null, 'Ab Crunch Machine', 'core', array['core'], 'machine', 'weight_reps', true),
  (null, 'Torso Rotation Machine', 'core', array['core'], 'machine', 'weight_reps', true),
  (null, 'Band Pallof Press', 'core', array['core'], 'band', 'weight_reps', true),
  (null, 'Weighted Sit-Up', 'core', array['core'], 'dumbbell', 'weight_reps', true),
  (null, 'Weighted Russian Twist', 'core', array['core'], 'dumbbell', 'weight_reps', true),

  -- ============ CARDIO ============
  (null, 'Outdoor Run', 'cardio', array['cardio'], 'bodyweight', 'distance_duration', true),
  (null, 'Stationary Bike', 'cardio', array['cardio'], 'machine', 'distance_duration', true),
  (null, 'Outdoor Cycling', 'cardio', array['cardio'], 'bodyweight', 'distance_duration', true),
  (null, 'Elliptical Trainer', 'cardio', array['cardio'], 'machine', 'distance_duration', true),
  (null, 'Stair Climber', 'cardio', array['cardio'], 'machine', 'distance_duration', true),
  (null, 'Swimming', 'cardio', array['cardio'], 'bodyweight', 'distance_duration', true),
  (null, 'Jump Rope', 'cardio', array['cardio'], 'bodyweight', 'time', true),
  (null, 'Sled Push', 'cardio', array['cardio','quadriceps'], 'machine', 'distance_duration', true),
  (null, 'Sled Pull', 'cardio', array['cardio','back'], 'machine', 'distance_duration', true),
  (null, 'Battle Ropes', 'cardio', array['cardio','shoulders'], 'bodyweight', 'time', true),
  (null, 'Burpee', 'cardio', array['cardio','core'], 'bodyweight', 'bodyweight_reps', true),
  (null, 'Box Jump', 'cardio', array['cardio','quadriceps'], 'bodyweight', 'bodyweight_reps', true)
on conflict do nothing;
